### ISSUE TITLE
Funny thing about the repo name

### ISSUE THREAD

**Issue by Justineo** [angusshire/greenhat#7]
In Chinese we say some man is “wearing a green hat” if his wife or girlfirend is cheating on him. :joy:

**Comment by threezj** [comment]
笑了。。

**Comment by frimin** [comment]
观光团前来围观。

**Comment by 4148** [comment]
中国人是优等民族。

**Comment by abalone0204** [comment]
XDDDDD

**Comment by DD-L** [comment]
hahahahahahahahaha

**Comment by luckymore** [comment]
> hahhaha

**Comment by NinjaRhyme** [comment]
233333

**Comment by shaunstanislaus** [comment]
有什么好笑。有病啊。

**Comment by yaochiqkl** [comment]
天了噜，好巧，前排围观顾大大
我只是随便点开的，看到了熟悉的足球头像…没想到真是，世界好小
（知乎粉）

**Comment by LLin233** [comment]
wearing green hat and turn your face into black.

**Comment by hengcj** [comment]
好神奇的账号~

**Comment by deanet** [comment]
lol  i thought that;s calendar true :joy:

**Comment by tucnak** [comment]
有什么好笑。有病啊。

**Comment by tucnak** [comment]
I copy-pasted some Chinese to look like Chinese, but I'm not.

**Comment by AlaeddineMessadi** [comment]
we should change to this ![logo](http://farm3.static.flickr.com/2485/4125074924_ab2f7ce235_b.jpg)

**Comment by kevinxh** [comment]
绿帽子... lol

**Comment by liushuaikobe** [comment]
A Swift version of this  https://github.com/liushuaikobe/green-Swift

**Comment by BroVic** [comment]
Is that where the phrase "green with envy" comes from? lol

**Comment by Naville** [comment]
很好笑？
一个技术社区发这张无营养的内容觉得自己很幽默？
你国的基础教育没教过你Issues这个词的意思？

傻逼

**Comment by agentready** [comment]
I fucked up by following this guy! :'(

**Comment by ventrciousn** [comment]
:hotsprings:

**Comment by cuisc13** [comment]
![eedc8caf9f364bcc9d2d65d4bbedb756_th](https://user-images.githubusercontent.com/5399228/27472507-3370874c-582e-11e7-9316-2ffa606775e5.png)

**Comment by zhangjh** [comment]
hahahah~I found this project because the author followed me. 
cultural difference.
